"""
Django settings for ic05backend project.

Generated by 'django-admin startproject' using Django 1.8.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
from ConfigParser import SafeConfigParser, NoSectionError, NoOptionError
from django.core.exceptions import ImproperlyConfigured

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'y8kqqt8j=h3d6&v5w!idnz8f86h*#awq9m_gcp!hu0_x)(v=)^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'utcaccounts',
    'visualizer',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'ic05backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ic05backend.wsgi.application'

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'


SETTINGS_PARSER = SafeConfigParser()
SETTINGS_PARSER.read(os.path.dirname(__file__) + '/local_settings.ini')


# GINGER INFO

GINGER_URL = 'https://assos.utc.fr/ginger/v1/'
GINGER_KEY = SETTINGS_PARSER.get('ginger', 'key')

AUTHENTICATION_BACKENDS = (
    'utcaccounts.backend.PayUTCAuthBackend',
)


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': SETTINGS_PARSER.get('database', 'engine'),
        'NAME': SETTINGS_PARSER.get('database', 'name'),
        'USER': SETTINGS_PARSER.get('database', 'user'),
        'PASSWORD': SETTINGS_PARSER.get('database', 'password'),
        'HOST': SETTINGS_PARSER.get('database', 'host'),
        'PORT': SETTINGS_PARSER.get('database', 'port'),
    }
}
"""except NoSectionError:
    raise ImproperlyConfigured("Server settings not defined properly")
except NoOptionError:
    raise ImproperlyConfigured("Server settings not defined properly")"""
